# Generated by Django 4.0.1 on 2022-02-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_delete_castomuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="region",
            field=models.IntegerField(
                choices=[
                    (1, "BISHKEK"),
                    (2, "OSH"),
                    (3, "TALAS"),
                    (4, "ISSYK KUL"),
                    (5, "NARYN"),
                    (6, "JALAL ABAD"),
                    (7, "BATKEN"),
                ],
                null=True,
                verbose_name="Регион",
            ),
        ),
    ]
