# Generated by Django 4.0.1 on 2022-02-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cloth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcl",
            options={"verbose_name": "Гардероб", "verbose_name_plural": "Гардеробы"},
        ),
        migrations.RenameField(
            model_name="productcl",
            old_name="type_clothing",
            new_name="discription",
        ),
    ]
